import { DispatchRecord } from '../types/dispatch';
import { generateSafeId } from './calculations';

export function getSampleDispatches(): DispatchRecord[] {
  const dsp1Id = generateSafeId('dsp_sample1');
  const dsp2Id = generateSafeId('dsp_sample2');
  const dsp3Id = generateSafeId('dsp_sample3');

  return [
    {
      id: dsp1Id,
      date: new Date(Date.now() - 86400000).toISOString().split('T')[0],
      fromParty: 'Tata Steel Processing Ltd',
      toParty: 'Larsen & Toubro Infra Projects',
      placement: 'Market',
      transporterName: 'Patel Roadways Logistics Ltd',
      vehicleNumber: 'MH 12 RN 4589',
      driverName: 'Ramesh Singh',
      driverPhone: '+91 98234 11204',
      lrNumbers: ['LR-MH-8901', 'LR-MH-8902'],
      totalWeight: 32.5,
      totalFreightAmount: 98500,
      totalAdvance: 40000,
      totalExtraCharges: 2500,
      netPayable: 61000,
      totalLrsCount: 2,
      // Market Vehicle Aggregates
      totalGrossMarketFreight: 88800,
      totalMarketCommission: 1500,
      totalMarketAdvance: 30000,
      totalNetMarketFreight: 57300,
      marketMargin: 9700,
      status: 'In Transit',
      notes: 'Steel coil consignment with high-grade strapping. Direct delivery to Yard 4.',
      createdAt: new Date(Date.now() - 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 86400000).toISOString(),
      ownerId: 'sample-user',
      syncStatus: 'synced',
      lrs: [
        {
          id: generateSafeId('lr'),
          lrNumber: 'LR-MH-8901',
          lrDate: new Date(Date.now() - 86400000).toISOString().split('T')[0],
          consignorName: 'Tata Steel Jamshedpur Works',
          consignorCity: 'Jamshedpur',
          consigneeName: 'L&T Metro Construction Yard',
          consigneeCity: 'Mumbai',
          invoiceNumbers: ['INV-TS-2026-091', 'INV-TS-2026-092'],
          ewaybillNumbers: ['121899014521', '121899014522'],
          weight: 22.0,
          weightUnit: 'MT',
          rate: 3000,
          rateType: 'per_mt',
          freightAmount: 66000,
          advanceAmount: 25000,
          extraCharges: 1500,
          remarks: 'HR Coils grade 350 - Handle with crane',
          // Market placement data scheme
          marketWeight: 22.0,
          marketRate: 2700,
          grossMarketFreight: 59400,
          marketCommission: 1000,
          marketAdvance: 20000,
          netMarketFreight: 38400,
          createdAt: new Date(Date.now() - 86400000).toISOString(),
          updatedAt: new Date(Date.now() - 86400000).toISOString(),
          ownerId: 'sample-user',
        },
        {
          id: generateSafeId('lr'),
          lrNumber: 'LR-MH-8902',
          lrDate: new Date(Date.now() - 86400000).toISOString().split('T')[0],
          consignorName: 'Tata Steel Structural Tube Plant',
          consignorCity: 'Jamshedpur',
          consigneeName: 'L&T Structural Depot',
          consigneeCity: 'Navi Mumbai',
          invoiceNumbers: ['INV-TST-4410'],
          ewaybillNumbers: ['181923091102'],
          weight: 10.5,
          weightUnit: 'MT',
          rate: 3100,
          rateType: 'per_mt',
          freightAmount: 32500,
          advanceAmount: 15000,
          extraCharges: 1000,
          remarks: 'Structural hollow sections with weatherproof tarpaulin',
          // Market placement data scheme
          marketWeight: 10.5,
          marketRate: 2800,
          grossMarketFreight: 29400,
          marketCommission: 500,
          marketAdvance: 10000,
          netMarketFreight: 18900,
          createdAt: new Date(Date.now() - 86400000).toISOString(),
          updatedAt: new Date(Date.now() - 86400000).toISOString(),
          ownerId: 'sample-user',
        },
      ],
    },
    {
      id: dsp2Id,
      date: new Date().toISOString().split('T')[0],
      fromParty: 'UltraTech Cement Corporation',
      toParty: 'Adani Infrastructure Terminal',
      placement: 'Own',
      transporterName: 'Own Company Fleet (Vehicle #12)',
      vehicleNumber: 'GJ 01 BV 8912',
      driverName: 'Suresh Parmar',
      driverPhone: '+91 97241 55901',
      lrNumbers: ['LR-GJ-1049'],
      totalWeight: 28.0,
      totalFreightAmount: 42000,
      totalAdvance: 15000,
      totalExtraCharges: 0,
      netPayable: 27000,
      totalLrsCount: 1,
      status: 'Confirmed',
      notes: 'PPC 53 Grade cement bags in 50kg packing. GPS enabled tanker.',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      ownerId: 'sample-user',
      syncStatus: 'synced',
      lrs: [
        {
          id: generateSafeId('lr'),
          lrNumber: 'LR-GJ-1049',
          lrDate: new Date().toISOString().split('T')[0],
          consignorName: 'UltraTech Cement Gujarat Plant',
          consignorCity: 'Kovaya',
          consigneeName: 'Adani Terminal Yard',
          consigneeCity: 'Mundra',
          invoiceNumbers: ['INV-UTC-7719', 'INV-UTC-7720'],
          ewaybillNumbers: ['241890048123', '241890048124'],
          weight: 28.0,
          weightUnit: 'MT',
          rate: 1500,
          rateType: 'per_mt',
          freightAmount: 42000,
          advanceAmount: 15000,
          extraCharges: 0,
          remarks: 'Standard 560 bags palletized load',
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
          ownerId: 'sample-user',
        },
      ],
    },
    {
      id: dsp3Id,
      date: new Date(Date.now() - 172800000).toISOString().split('T')[0],
      fromParty: 'Reliance Polymer Logistics',
      toParty: 'Supreme Industries Plast',
      placement: 'Market',
      transporterName: 'Southern Roadways Express',
      vehicleNumber: 'DL 01 AA 7731',
      driverName: 'Mukesh Yadav',
      driverPhone: '+91 99112 00482',
      lrNumbers: ['LR-DL-5521', 'LR-DL-5522', 'LR-DL-5523'],
      totalWeight: 21.0,
      totalFreightAmount: 73500,
      totalAdvance: 35000,
      totalExtraCharges: 3000,
      netPayable: 41500,
      totalLrsCount: 3,
      // Market Vehicle Aggregates
      totalGrossMarketFreight: 66000,
      totalMarketCommission: 1500,
      totalMarketAdvance: 25000,
      totalNetMarketFreight: 39500,
      marketMargin: 7500,
      status: 'Delivered',
      notes: 'Delivered and POD acknowledged by receiving warehouse manager.',
      createdAt: new Date(Date.now() - 172800000).toISOString(),
      updatedAt: new Date(Date.now() - 172800000).toISOString(),
      ownerId: 'sample-user',
      syncStatus: 'synced',
      lrs: [
        {
          id: generateSafeId('lr'),
          lrNumber: 'LR-DL-5521',
          lrDate: new Date(Date.now() - 172800000).toISOString().split('T')[0],
          consignorName: 'Reliance Polymers Hazira',
          consignorCity: 'Hazira',
          consigneeName: 'Supreme Industries Unit 1',
          consigneeCity: 'Noida',
          invoiceNumbers: ['INV-RIL-9011'],
          ewaybillNumbers: ['331908221004'],
          weight: 8.0,
          weightUnit: 'MT',
          rate: 3500,
          rateType: 'per_mt',
          freightAmount: 28000,
          advanceAmount: 12000,
          extraCharges: 1000,
          remarks: 'HDPE Granules Grade F46003',
          // Market placement data scheme
          marketWeight: 8.0,
          marketRate: 3100,
          grossMarketFreight: 24800,
          marketCommission: 500,
          marketAdvance: 10000,
          netMarketFreight: 14300,
          createdAt: new Date(Date.now() - 172800000).toISOString(),
          updatedAt: new Date(Date.now() - 172800000).toISOString(),
          ownerId: 'sample-user',
        },
        {
          id: generateSafeId('lr'),
          lrNumber: 'LR-DL-5522',
          lrDate: new Date(Date.now() - 172800000).toISOString().split('T')[0],
          consignorName: 'Reliance Polymers Hazira',
          consignorCity: 'Hazira',
          consigneeName: 'Supreme Industries Unit 2',
          consigneeCity: 'Greater Noida',
          invoiceNumbers: ['INV-RIL-9012'],
          ewaybillNumbers: ['331908221005'],
          weight: 7.0,
          weightUnit: 'MT',
          rate: 3500,
          rateType: 'per_mt',
          freightAmount: 24500,
          advanceAmount: 11000,
          extraCharges: 1000,
          remarks: 'LLDPE Film extrusion grade',
          // Market placement data scheme
          marketWeight: 7.0,
          marketRate: 3150,
          grossMarketFreight: 22050,
          marketCommission: 500,
          marketAdvance: 8000,
          netMarketFreight: 13550,
          createdAt: new Date(Date.now() - 172800000).toISOString(),
          updatedAt: new Date(Date.now() - 172800000).toISOString(),
          ownerId: 'sample-user',
        },
        {
          id: generateSafeId('lr'),
          lrNumber: 'LR-DL-5523',
          lrDate: new Date(Date.now() - 172800000).toISOString().split('T')[0],
          consignorName: 'Reliance Polymers Hazira',
          consignorCity: 'Hazira',
          consigneeName: 'Supreme Industries Moldings',
          consigneeCity: 'Faridabad',
          invoiceNumbers: ['INV-RIL-9013', 'INV-RIL-9014'],
          ewaybillNumbers: ['331908221006'],
          weight: 6.0,
          weightUnit: 'MT',
          rate: 3500,
          rateType: 'per_mt',
          freightAmount: 21000,
          advanceAmount: 12000,
          extraCharges: 1000,
          remarks: 'PP Injection molding compound',
          // Market placement data scheme
          marketWeight: 6.0,
          marketRate: 3190,
          grossMarketFreight: 19140,
          marketCommission: 500,
          marketAdvance: 7000,
          netMarketFreight: 11640,
          createdAt: new Date(Date.now() - 172800000).toISOString(),
          updatedAt: new Date(Date.now() - 172800000).toISOString(),
          ownerId: 'sample-user',
        },
      ],
    },
  ];
}
